header-from: ./.config/header.md

version: ""

formatter: markdown table

name: Single-Account-Starter

content: |-
 {{ .Header }}
 
  # terraform-aws-single-account-starter

  GitHub: [StratusGrid/terraform-aws-single-account-starter](https://github.com/StratusGrid/terraform-aws-single-account-starter)

  ### Template Documentation

  This is to showcase the use of many StratusGrid and Community modules working together to configure a single account architecture using terraform version 1.x or higher.

  ### ToDo
  - Wrap with templating language to output a custom from GUI.
  -- Primary Region and which Regions to add
  -- Whether to do vm import role and bucket

  ### Init:
  ```
  awsudo -u \<profile\> terraform init
  ```

  ### Apply:
  ```
  awsudo -u \<profile\> terraform apply -var region=us-east-1 -var name_prefix=\<prefix\> -var env_name=\<env\> -var source_repo=\<repo\>
  ```

  ## Recommended first steps if using this as the account code

  - Enable IAM Billing access while logged in as root under My Account
  - Delete the default VPCs in all regions you will be using (at least all regions with config rules...)
  - Tag the default RDS DB Security Groups in all regions with your required tags (cli to do so is below)

  ```
  awsudo -u \<profile\> aws rds add-tags-to-resource --resource-name "arn:aws:rds:us-east-1:<account_number>:secgrp:default" --tags Key=Environment,Value=prd,Key=Customer,Value=Shared --region us-east-1

  awsudo -u \<profile\> aws rds add-tags-to-resource --resource-name "arn:aws:rds:us-east-2:<account_number>:secgrp:default" --tags Key=Environment,Value=prd,Key=Customer,Value=Shared --region us-east-2

  awsudo -u \<profile\> aws rds add-tags-to-resource --resource-name "arn:aws:rds:us-west-1:<account_number>:secgrp:default" --tags Key=Environment,Value=prd,Key=Customer,Value=Shared --region us-west-1

  awsudo -u \<profile\> aws rds add-tags-to-resource --resource-name "arn:aws:rds:us-west-2:<account_number>:secgrp:default" --tags Key=Environment,Value=prd,Key=Customer,Value=Shared --region us-west-2
  ```
  - Enable updated account features for ECS
  ```
  awsudo -u \<profile\> aws ecs put-account-setting-default --name serviceLongArnFormat --value enabled --region us-east-1
  awsudo -u \<profile\> aws ecs put-account-setting-default --name taskLongArnFormat --value enabled --region us-east-1
  awsudo -u \<profile\> aws ecs put-account-setting-default --name containerInstanceLongArnFormat --value enabled --region us-east-1
  awsudo -u \<profile\> aws ecs put-account-setting-default --name awsvpcTrunking --value enabled --region us-east-1
  awsudo -u \<profile\> aws ecs put-account-setting-default --name containerInsights --value enabled --region us-east-1
  ```

  ## Recommended final steps
  ### Change Terraform backend to S3

  1. Update `state.tf` using the output values from a successful `terraform apply`. Then rename to `state.tf`.
  2. Run `terraform init` to update Terrafrom to use S3 bucket as a backend:
  ```
  awsudo -u \<profile\> terraform init
  ```

  ### Add existing IAM users to new groups

  1. From the AWS Management Console, open Identity and Access Management.
  2. Add all existing users who will require admin access to the new restricted-admin group. 

  ## Tools to Use

  - awsudo
  - tfenv (if using multiple versions of terraform)

  ---

  Note: Before reading, uncomment the code for the environment that you
  wish to apply the code to. This goes for both the init-tfvars and apply-tfvars
  folders.
  
  ---

  ## GitHub actions pre-commit workflow

  Use the following command to pre-populate hashes for Linux and avoid error messages in the terraform_validate step of GitHub actions pre-commit workflow.

  ```bash
  terraform providers lock -platform=linux_amd64
  ```

  Execute the command in folders that contain the file .terraform.lock.hcl such as the root folder and modules folders.


  {{ .Requirements }}

  {{ .Resources }}

  {{ .Inputs }}

  {{ .Outputs }}

  ---

  Note, manual changes to the README will be overwritten when the documentation is updated. To update the documentation, run `terraform-docs -c .config/.terraform-docs.yml`

sections:
  show:
    - header
    - requirements
    - resources
    - inputs
    - outputs

sort:
  enabled: true
  by: name

output:
  file: README.md
  mode: replace
